# Generated by Django 4.2.1 on 2023-06-16 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
