# Generated by Django 4.2.1 on 2023-06-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static/base/profile_picture.jpg', upload_to='photos/profile/'),
        ),
    ]
