# Generated by Django 4.2.1 on 2023-06-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../static/base/profile_picture.jpg', null=True, upload_to='photos/profile/'),
        ),
    ]
