# Generated by Django 4.2.1 on 2023-07-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_delete_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='following',
        ),
    ]
