# Generated by Django 4.2.1 on 2023-07-30 02:54

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_friends_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='friends',
        ),
    ]
