# Generated by Django 4.2.1 on 2023-07-30 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='accepted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
