# Generated by Django 4.2.1 on 2023-08-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
