# Generated by Django 4.2.1 on 2023-08-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_friendrequest_canceled_on_friendrequest_is_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_canceled',
            new_name='was_canceled',
        ),
    ]
