# Generated by Django 4.2.5 on 2023-09-14 23:37

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_is_canceled_friendrequest_was_canceled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.managers.UserManager()),
            ],
        ),
    ]
