# Generated by Django 4.2.5 on 2023-09-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biography',
            new_name='description',
        ),
    ]
