# Generated by Django 4.2.5 on 2023-09-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_rename_biography_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='was_canceled',
            new_name='is_canceled',
        ),
    ]
