# Generated by Django 4.2.5 on 2023-09-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_user_description_user_profile_image_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='following',
        ),
    ]
