# Generated by Django 4.2.5 on 2023-09-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_followrequest_alter_user_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='request_date',
        ),
    ]
