# Generated by Django 4.2.5 on 2023-09-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
