# Generated by Django 4.2.5 on 2023-09-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_delete_followrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
            ],
        ),
    ]
