# Generated by Django 4.2.5 on 2023-09-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_matchup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
