# Generated by Django 4.2.5 on 2023-09-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_matchup_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
