# Generated by Django 4.2.5 on 2023-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_week_alter_matchup_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='week',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
