# Generated by Django 4.2.5 on 2023-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_matchup_away_score_alter_matchup_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
