# Generated by Django 4.2.5 on 2023-09-23 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_matchup_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('season_type', models.CharField(choices=[('Pre', 'Preseason'), ('Reg', 'Regular season'), ('Post', 'Postseason')], max_length=50)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
