# Generated by Django 4.2.5 on 2023-09-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_week_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='season_type',
        ),
    ]
