# Generated by Django 4.2.5 on 2023-09-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_remove_week_season_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
