# Generated by Django 4.2.5 on 2023-09-24 19:30

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_pickgroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('profile_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
