# Generated by Django 4.2.5 on 2023-09-24 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_user_managers_alter_matchup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickgroup',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
