# Generated by Django 4.2.5 on 2023-09-25 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_pickgroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 20, 22, 32, 704176)),
        ),
    ]
