# Generated by Django 4.2.5 on 2023-09-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_matchup_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='last_updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
