# Generated by Django 4.2.5 on 2023-09-25 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_matchup_date_alter_matchup_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 2, 8, 50, 321387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 2, 8, 50, 321512, tzinfo=datetime.timezone.utc)),
        ),
    ]
