# Generated by Django 4.2.5 on 2023-09-25 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_matchup_date_alter_matchup_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
