# Generated by Django 4.2.5 on 2023-09-26 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_matchup_date_alter_matchup_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickgroup',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('1', 'Home'), ('2', 'Away')])),
                ('is_correct', models.BooleanField(default=False)),
                ('matchup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of', to='base.matchup')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_picks', to=settings.AUTH_USER_MODEL)),
                ('pick_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of', to='base.pickgroup')),
            ],
        ),
    ]
