# Generated by Django 4.2.5 on 2023-09-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_pickgroup_can_invite_alter_pick_matchup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickgroup',
            name='can_invite',
        ),
    ]
