# Generated by Django 4.2.5 on 2023-09-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_remove_pickgroup_can_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='winner',
            field=models.CharField(blank=True, choices=[('1', 'Home'), ('2', 'Away')]),
        ),
    ]
