# Generated by Django 4.2.5 on 2023-09-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_matchup_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='selection',
            field=models.CharField(blank=True, choices=[('1', 'Home'), ('2', 'Away')]),
        ),
    ]
